services:
  application:
    build: .
    depends_on:
      - redis
      - mongo
    volumes:
      - ./:/data
    ports:
      - '8080:8080'
  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - '6379:6379'
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'
